const burgers = [
    {
        id: 1,
        name: 'Le Fuego Inferno',
        cooker:"Santiago Alvarez",
        price: 7,
        picture: "/images/fuego-inferno.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"fromage",
        description:"Le burger le plus épicé de la carte !",
        RestaurantId: 1,
        created: new Date()
    },
    {
        id: 2,
        name: 'Le Mac Attack',
        cooker:"Paul Bopin",
        price: 8,
        picture: "/images/mac-attack.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 1,
        created: new Date()
    },
    {
        id: 3,
        name: 'Le Veggie Delight',
        cooker:"",
        price: 6,
        picture: "/images/veggie-delight.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 2,
        created: new Date()
    },
    {
        id: 4,
        name: "Le Surf n' Turf",
        cooker:"",
        price: 7,
        picture: "/images/surf-n-turf.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 2,
        created: new Date()
    },
    {
        id: 5,
        name: 'Le Breakfast Bomb',
        cooker:"",
        price: 9,
        picture: "/images/breakfast-bomb.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 2,
        created: new Date()
    },
    {
        id: 6,
        name: "Le Smokin' BBQ",
        cooker:"",
        price: 7,
        picture: "/images/smokin-bbq.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 3,
        created: new Date()
    },
    {
        id: 7,
        name: 'Le Truffle Shuffle',
        cooker:"",
        price: 8,
        picture: "/images/truffle-shuffle.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 3,
        created: new Date()
    },
    {
        id: 8,
        name: 'Le Blue Hawaiian',
        cooker:"",
        price: 7,
        picture: "/images/blue-hawaiian.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 3,
        created: new Date()
    },
    {
        id: 9,
        name: 'Le Southern Charm',
        cooker:"",
        price: 6,
        picture: "/images/southern-charm.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 4,
        created: new Date()
    },
    {
        id: 10,
        name: 'Le Nacho Libre',
        cooker:"",
        price: 8,
        picture: "/images/nacho-libre.jpg",
        garniture:"boeuf",
        garniture2:"bacon",
        fromage:"cheddar",
        legumes:["salade", "tomate", "oignon"],
        sauce:"ketchup",
        description:"",
        RestaurantId: 4,
        created: new Date()
    }
]

module.exports = burgers;